"""Local, SQLite-backed scheduling and notification foundations."""

from marvis.operations.contracts import (
    CALENDAR_SCHEMA_VERSION,
    HUMAN_ESCALATION_SCHEMA_VERSION,
    MAX_CATCH_UP_BUDGET,
    MAX_RETRY_ATTEMPTS,
    MONITORING_OUTCOME_SCHEMA_VERSION,
    RETRY_SCHEMA_VERSION,
    SCHEDULE_SCHEMA_VERSION,
    CalendarPeriod,
    FixedIntervalCalendar,
    HumanEscalationSuggestion,
    MonitoringOutcome,
    RetryPolicy,
    ScheduleContract,
)
from marvis.operations.repository import (
    EventRecord,
    NotificationClaim,
    NotificationRecord,
    OutcomeRecord,
    OperationsStore,
    PeriodRecord,
    RunClaim,
    RunRecord,
    ScheduleRecord,
    ScheduleRevisionConflict,
    StaleNotificationLeaseError,
    StaleRunLeaseError,
)
from marvis.operations.notifications import (
    REDACTED_NOTIFICATION_SCHEMA_VERSION,
    NotificationAdapter,
    NotificationRedactor,
    RedactedNotification,
)
from marvis.operations.schema import (
    OPERATIONS_SCHEMA_VERSION,
    OperationsSchemaVersionError,
    install_operations_schema,
)
from marvis.operations.scheduler import (
    LocalScheduler,
    MonitoringExecutor,
    ScheduledRunRequest,
    TickReport,
)
from marvis.operations.integration import (
    OperationsRuntime,
    RecoveryReport,
    UnknownMonitoringReference,
    build_operations_runtime,
)

__all__ = [
    "CALENDAR_SCHEMA_VERSION",
    "HUMAN_ESCALATION_SCHEMA_VERSION",
    "MAX_CATCH_UP_BUDGET",
    "MAX_RETRY_ATTEMPTS",
    "MONITORING_OUTCOME_SCHEMA_VERSION",
    "RETRY_SCHEMA_VERSION",
    "SCHEDULE_SCHEMA_VERSION",
    "CalendarPeriod",
    "FixedIntervalCalendar",
    "HumanEscalationSuggestion",
    "MonitoringOutcome",
    "MonitoringExecutor",
    "NotificationAdapter",
    "NotificationClaim",
    "NotificationRecord",
    "NotificationRedactor",
    "EventRecord",
    "OutcomeRecord",
    "OPERATIONS_SCHEMA_VERSION",
    "OperationsSchemaVersionError",
    "OperationsStore",
    "OperationsRuntime",
    "PeriodRecord",
    "REDACTED_NOTIFICATION_SCHEMA_VERSION",
    "RecoveryReport",
    "RedactedNotification",
    "RetryPolicy",
    "RunClaim",
    "RunRecord",
    "LocalScheduler",
    "ScheduleContract",
    "ScheduleRecord",
    "ScheduleRevisionConflict",
    "StaleNotificationLeaseError",
    "StaleRunLeaseError",
    "ScheduledRunRequest",
    "TickReport",
    "UnknownMonitoringReference",
    "build_operations_runtime",
    "install_operations_schema",
]
