from __future__ import annotations

from marvis.llm_prompts import AGENT_SYSTEM_PROMPT as _AGENT_SYSTEM_PROMPT_SPEC
from marvis.llm_prompts import RISK_METRIC_INTERPRETATION_GUIDANCE as RISK_METRIC_INTERPRETATION_GUIDANCE
from marvis.llm_prompts import WORD_CONCLUSION_SYSTEM_PROMPT as _WORD_CONCLUSION_SYSTEM_PROMPT_SPEC
from marvis.llm_prompts import WORD_CONCLUSION_V2_SYSTEM_PROMPT as _WORD_CONCLUSION_V2_SYSTEM_PROMPT_SPEC


# LLM-10: text/version now live in marvis.llm_prompts; kept as module-level
# constants so existing imports of AGENT_SYSTEM_PROMPT / WORD_CONCLUSION_SYSTEM_PROMPT
# from here keep working unchanged.
AGENT_SYSTEM_PROMPT = _AGENT_SYSTEM_PROMPT_SPEC.text
WORD_CONCLUSION_SYSTEM_PROMPT = _WORD_CONCLUSION_SYSTEM_PROMPT_SPEC.text
WORD_CONCLUSION_V2_SYSTEM_PROMPT = _WORD_CONCLUSION_V2_SYSTEM_PROMPT_SPEC.text
