"""Independent numerical examples, not expected values generated by the producer."""
from dataclasses import replace

import pandas as pd
import pytest

from marvis.orchestrator.eval.runtime_labeling_reference import reference_labels
from marvis.packs.labeling.contracts import LabelingRequest


def request(**changes):
    values = dict(dataset_id="source", expected_content_hash="a" * 64, workspace_revision=1, analysis_generation=0,
                  id_col="loan", mob_col="mob", cohort_col="cohort", date_col="date", as_of_date="2026-04-30",
                  target_col="bad", observation_window=1, performance_window=3, at_mob=3,
                  rule_kind="dpd", dpd_col="dpd", threshold_dpd=90)
    return LabelingRequest(**{**values, **changes})


def frame(rows):
    return pd.DataFrame(rows, columns=["loan", "mob", "cohort", "date", "dpd"])


def test_reference_respects_window_cutoff_early_bad_and_nonbad_maturity():
    rows = frame([
        ["before-window", 1, "202601", "2026-01-31", 100],
        ["before-window", 3, "202601", "2026-03-31", 0],
        ["bad-before-maturity", 2, "202602", "2026-02-28", 90],
        ["not-yet-bad", 2, "202602", "2026-02-28", 89.999],
        ["not-yet-bad", 3, "202602", "2026-05-01", 100],
        ["mature-after-gap", 4, "202601", "2026-04-30", 100],
    ])
    result = reference_labels(rows, request())
    assert result["frame"]["loan"].tolist() == ["before-window", "bad-before-maturity", "not-yet-bad", "mature-after-gap"]
    assert result["frame"]["bad"].iloc[[0, 1, 3]].tolist() == [0.0, 1.0, 0.0]
    assert pd.isna(result["frame"]["bad"].iloc[2])
    assert result["quality"] == {"n_loans": 4, "n_bad": 1, "n_good": 2, "n_unmatured": 1,
                                 "label_coverage": 0.75, "bad_rate": 1 / 3}
    assert result["rows_at_as_of"] == 5 and result["rows_excluded_after_as_of"] == 1
    assert result["maturity"] == {"required_mob": 3, "cohorts": [
        {"cohort": "2026-01", "n_loans": 2, "max_observed_mob": 4, "required_mob": 3, "matured": True},
        {"cohort": "2026-02", "n_loans": 2, "max_observed_mob": 2, "required_mob": 3, "matured": False},
    ], "immature_cohorts": ["2026-02"], "all_matured": False}


def test_status_rule_uses_declared_bucket_order_instead_of_lexical_order():
    data = frame([
        ["hit", 2, "2026-01", "2026-02-28", "B"],
        ["nonhit", 3, "2026-01", "2026-03-31", "Z"],
        ["early", 1, "2026-01", "2026-01-31", "B"],
        ["early", 3, "2026-01", "2026-03-31", "Z"],
    ]).rename(columns={"dpd": "state"})
    contract = request(rule_kind="status", dpd_col=None, threshold_dpd=None,
                       status_col="state", states=["Z", "A", "B"], threshold_status="A")
    result = reference_labels(data, contract)
    assert result["frame"]["bad"].tolist() == [1.0, 0.0, 0.0]
    assert result["bad_definition"]["label"] == "A+@mob3 (obs=1, perf=3)"


def test_fractional_threshold_is_preserved_in_labels_and_definition():
    data = frame([["below", 3, "2026-01", "2026-03-31", 90.4], ["at", 3, "2026-01", "2026-03-31", 90.5]])
    result = reference_labels(data, request(threshold_dpd=90.5))
    assert result["frame"]["bad"].tolist() == [0.0, 1.0]
    assert result["bad_definition"]["threshold"] == 90.5
    assert result["bad_definition"]["label"] == "DPD90.5+@mob3 (obs=1, perf=3)"


def test_threshold_explanation_keeps_precision_beyond_six_significant_digits():
    data = frame([["below", 3, "2026-01", "2026-03-31", 90.1234566], ["at", 3, "2026-01", "2026-03-31", 90.1234567]])
    result = reference_labels(data, request(threshold_dpd=90.1234567))
    assert result["frame"]["bad"].tolist() == [0.0, 1.0]
    assert result["bad_definition"]["label"] == "DPD90.1234567+@mob3 (obs=1, perf=3)"


def test_unknown_labels_are_not_filled_with_zero_or_included_in_bad_rate_denominator():
    result = reference_labels(frame([["pending", 2, "2026-01", "2026-02-28", 0]]), request())
    assert result["quality"] == {"n_loans": 1, "n_bad": 0, "n_good": 0, "n_unmatured": 1,
                                 "label_coverage": 0.0, "bad_rate": None}
    assert pd.isna(result["frame"]["bad"].iloc[0])


@pytest.mark.parametrize("value", [-1, 1.5, float("inf")])
def test_reference_rejects_invalid_mob(value):
    with pytest.raises(ValueError, match="invalid observed MOB"):
        reference_labels(frame([["one", value, "2026-01", "2026-01-31", 0]]), request())


@pytest.mark.parametrize("mutation", ["date", "cohort", "loan", "columns", "target", "cohort_drift"])
def test_reference_rejects_ambiguous_source_identity_and_time(mutation):
    data = frame([["one", 2, "2026-01", "2026-02-28", 0]])
    if mutation == "date":
        data.loc[0, "date"] = "not-a-date"
    elif mutation == "cohort":
        data.loc[0, "cohort"] = "202613"
    elif mutation == "loan":
        data.loc[0, "loan"] = None
    elif mutation == "columns":
        with pytest.raises(ValueError):
            reference_labels(data, replace(request(), mob_col="loan"))
        return
    elif mutation == "target":
        data["bad"] = 0
    else:
        data.loc[1] = ["one", 3, "2026-02", "2026-03-31", 0]
    with pytest.raises(ValueError):
        reference_labels(data, request())
