"""Deterministic delivery code for committed automatic rule-tree leaves.

The public generators accept either a strict weighted-tree result or a strict
automatic-tree candidate asset. Both outputs route rows to stable leaf/rule
identities only; business actions remain outside this delivery boundary. Public
Python delivery enforces missing or finite, float-representable ``Real`` feature
values. DuckDB delivery is intentionally narrower: registered feature columns must
pass the mandatory frame/schema preflight, have integer/float physical types, and
contain only integers exactly representable as ``DOUBLE``. It never coerces strings,
booleans, decimals, or arbitrary objects.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from numbers import Real
from string import Template
from typing import Any

import duckdb
import pandas as pd

from marvis.feature.weighted_rule_tree import (
    WEIGHTED_RULE_TREE_SCHEMA_VERSION,
    WeightedRuleTreeError,
    validate_weighted_rule_tree,
)
from marvis.packs.strategy.automatic_tree_asset import (
    AUTOMATIC_TREE_ASSET_SCHEMA_VERSION,
    AutomaticTreeAssetError,
    validate_automatic_tree_asset,
)
from marvis.packs.strategy.dsl import canonicalize_expression
from marvis.packs.strategy.errors import StrategyError


class AutomaticTreeCodegenError(StrategyError):
    """The requested automatic-tree source cannot be generated safely."""


_DUCKDB_INTEGER_TYPES = (
    "TINYINT",
    "SMALLINT",
    "INTEGER",
    "BIGINT",
    "HUGEINT",
    "UTINYINT",
    "USMALLINT",
    "UINTEGER",
    "UBIGINT",
    "UHUGEINT",
)
_DUCKDB_FLOAT_TYPES = ("FLOAT", "DOUBLE")
_MAX_EXACT_DOUBLE_INTEGER = 2**53


_PYTHON_TEMPLATE = Template('''# Generated by MARVIS automatic-tree codegen. Do not edit.
# Public delivery accepts missing or finite, float-representable Python Real features.
from __future__ import annotations

import json as _json
import math as _math
from collections.abc import Iterable, Mapping
from numbers import Integral, Real
from typing import Any

import numpy as _np
import pandas as _pd


_RULES = _json.loads($marvis_rules_json_literal)
_REQUIRED_FIELDS = tuple(_json.loads($marvis_fields_json_literal))
_ENFORCE_WEIGHTED_TREE_DOMAIN = $marvis_enforce_weighted_tree_domain


def _is_missing(value: Any) -> bool:
    if value is None:
        return True
    try:
        marker = _pd.isna(value)
        return bool(marker) if isinstance(marker, bool | Integral) else False
    except (TypeError, ValueError):
        return False


def _numeric_literal(value: Any) -> bool:
    return isinstance(value, Real) and not isinstance(value, bool)


def _boolean_literal(value: Any) -> bool:
    return isinstance(value, (bool, _np.bool_))


def _strict_equal(value: Any, expected: Any) -> bool:
    if _boolean_literal(expected):
        return _boolean_literal(value) and bool(value) is bool(expected)
    if _numeric_literal(expected):
        return _numeric_literal(value) and bool(value == expected)
    if isinstance(expected, str):
        return isinstance(value, str) and value == expected
    return value is expected


def _coerce_numeric(value: Any) -> int | float:
    if _is_missing(value):
        raise ValueError("condition comparison failed: field value is missing")
    try:
        numeric = _pd.to_numeric(value, errors="coerce")
    except (TypeError, ValueError) as exc:
        raise ValueError("condition comparison failed") from exc
    if _is_missing(numeric):
        raise ValueError(
            "condition comparison failed: field contains a non-numeric value"
        )
    if isinstance(numeric, Integral):
        return int(numeric)
    return float(numeric)


def _missing_result(value: Any, policy: str) -> bool | None:
    if not _is_missing(value):
        return None
    if policy == "no_match":
        return False
    if policy == "match":
        return True
    if policy == "error":
        raise ValueError("condition comparison failed: field value is missing")
    raise ValueError(f"unsupported missing policy: {policy}")


def _compare(
    value: Any,
    operator: str,
    expected: Any,
    *,
    missing: str,
    coercion: str = "auto",
) -> bool:
    missing_result = _missing_result(value, missing)
    if missing_result is not None:
        return missing_result
    if coercion == "strict":
        if operator in {"in", "not_in"}:
            matched = any(_strict_equal(value, item) for item in expected)
            return matched if operator == "in" else not matched
        matched = _strict_equal(value, expected)
        return matched if operator == "==" else not matched
    try:
        if operator in {"in", "not_in"}:
            candidates = list(expected)
            if candidates and all(_numeric_literal(item) for item in candidates):
                value = _coerce_numeric(value)
            matched = value in candidates
            return matched if operator == "in" else not matched
        if _numeric_literal(expected):
            value = _coerce_numeric(value)
        if operator == "<":
            return bool(value < expected)
        if operator == "<=":
            return bool(value <= expected)
        if operator == ">":
            return bool(value > expected)
        if operator == ">=":
            return bool(value >= expected)
        if operator == "==":
            return bool(value == expected)
        if operator == "!=":
            return bool(value != expected)
    except (TypeError, ValueError) as exc:
        raise ValueError("condition comparison failed") from exc
    raise ValueError(f"unsupported comparison operator: {operator}")


def _between(value: Any, expression: Mapping[str, Any]) -> bool:
    missing_result = _missing_result(value, expression["missing"])
    if missing_result is not None:
        return missing_result
    lower = expression["lower"]
    upper = expression["upper"]
    if _numeric_literal(lower) and _numeric_literal(upper):
        value = _coerce_numeric(value)
    try:
        lower_match = value >= lower if expression["include_lower"] else value > lower
        upper_match = value <= upper if expression["include_upper"] else value < upper
        return bool(lower_match and upper_match)
    except (TypeError, ValueError) as exc:
        raise ValueError("condition comparison failed") from exc


def _lookup(row: Mapping[str, Any], field: str) -> Any:
    try:
        if field not in row:
            raise ValueError(f"unknown field: {field}")
        return row[field]
    except (KeyError, TypeError):
        raise ValueError(f"unknown field: {field}") from None


def _evaluate(row: Mapping[str, Any], expression: Mapping[str, Any]) -> bool:
    op = expression["op"]
    if op == "compare":
        return _compare(
            _lookup(row, expression["field"]),
            expression["operator"],
            expression["value"],
            missing=expression["missing"],
            coercion=expression.get("coercion", "auto"),
        )
    if op == "between":
        return _between(_lookup(row, expression["field"]), expression)
    if op == "is_null":
        return _is_missing(_lookup(row, expression["field"]))
    if op == "is_not_null":
        return not _is_missing(_lookup(row, expression["field"]))
    if op == "and":
        return all(_evaluate(row, argument) for argument in expression["args"])
    if op == "or":
        return any(_evaluate(row, argument) for argument in expression["args"])
    if op == "not":
        return not _evaluate(row, expression["arg"])
    if op == "n_of_k":
        matched = 0
        for argument in expression["args"]:
            matched += int(_evaluate(row, argument))
            if matched >= expression["n"]:
                return True
        return False
    raise ValueError(f"unsupported expression op: {op}")


def _assert_row(row: Any) -> None:
    if not isinstance(row, Mapping) and not isinstance(row, _pd.Series):
        raise ValueError("strategy row must be a mapping")


def _prevalidate_row(row: Mapping[str, Any]) -> None:
    _assert_row(row)
    for field in _REQUIRED_FIELDS:
        value = _lookup(row, field)
        if not _ENFORCE_WEIGHTED_TREE_DOMAIN or _is_missing(value):
            continue
        valid_numeric = not isinstance(
            value, bool | str | bytes | bytearray
        ) and isinstance(value, Real)
        if valid_numeric:
            try:
                valid_numeric = _math.isfinite(float(value))
            except (OverflowError, TypeError, ValueError):
                valid_numeric = False
        if not valid_numeric:
            raise ValueError(
                f"weighted-tree numeric feature `{field}` must be missing "
                "or a finite, float-representable Python Real"
            )


def _apply_prevalidated(row: Mapping[str, Any]) -> dict[str, str]:
    matched = []
    for rule in _RULES:
        if _evaluate(row, rule["condition"]):
            matched.append(rule)
    if len(matched) != 1:
        raise RuntimeError("leaf rules must assign every row exactly once")
    return {"leaf_id": matched[0]["leaf_id"], "rule_id": matched[0]["rule_id"]}


def apply_row(row: Mapping[str, Any]) -> dict[str, str]:
    """Route one mapping to exactly one stable leaf/rule identity."""

    _prevalidate_row(row)
    return _apply_prevalidated(row)


def apply_rows(rows: Iterable[Mapping[str, Any]] | _pd.DataFrame) -> list[dict[str, str]]:
    """Route rows after validating every referenced field for the full batch."""

    if isinstance(rows, _pd.DataFrame):
        duplicate_columns = rows.columns[rows.columns.duplicated()].tolist()
        if duplicate_columns:
            names = ", ".join(str(column) for column in duplicate_columns)
            raise ValueError(f"strategy frame has duplicate columns: {names}")
        for field in _REQUIRED_FIELDS:
            occurrences = sum(column == field for column in rows.columns)
            if occurrences == 0:
                raise ValueError(f"unknown field: {field}")
            if occurrences > 1:
                raise ValueError(f"strategy field must identify one column: {field}")
        materialized = rows.to_dict(orient="records")
    else:
        try:
            materialized = list(rows)
        except TypeError as exc:
            raise ValueError("strategy rows must be iterable") from exc
    for row in materialized:
        _prevalidate_row(row)
    return [_apply_prevalidated(row) for row in materialized]


__all__ = ["apply_row", "apply_rows"]
''')


def generate_automatic_tree_python_source(
    tree_or_asset: Mapping[str, Any],
) -> str:
    """Return Python enforcing the weighted-tree finite-Real input domain."""

    return _generate_python_source_from_leaf_rules(
        _validated_leaf_rules(tree_or_asset),
        enforce_weighted_tree_domain=True,
    )


def generate_automatic_tree_duckdb_sql_source(
    tree_or_asset: Mapping[str, Any],
) -> str:
    """Return numeric-domain DuckDB SQL reading the fixed ``input_rows`` relation.

    The SQL selects required columns by exact-case name, rejects non-integer/float
    physical types and lossy integers, and enables insertion-order preservation
    before assigning its internal row ordinal. The caller must run
    :func:`validate_automatic_tree_duckdb_input_frame` on the same unmodified frame
    immediately before registering ``input_rows``. SQL alone cannot recover the
    original schema after DuckDB has renamed colliding columns.
    """

    return _generate_duckdb_sql_from_leaf_rules(_validated_leaf_rules(tree_or_asset))


def validate_automatic_tree_duckdb_input_frame(
    frame: pd.DataFrame,
    tree_or_asset: Mapping[str, Any],
    *,
    additional_feature_fields: Sequence[str] | None = None,
) -> pd.DataFrame:
    """Enforce the mandatory schema and value-domain DuckDB preflight.

    Call this immediately before registering the same, unmodified ``frame`` as
    ``input_rows``. The returned object is the original frame, not a copy. Tools
    may supply ``additional_feature_fields`` to validate selected training
    features that a fitted tree did not ultimately reference; expression fields
    are always included and cannot be removed.
    """

    rules = _validated_leaf_rules(tree_or_asset)
    if not isinstance(frame, pd.DataFrame):
        raise AutomaticTreeCodegenError("DuckDB input must be a pandas DataFrame")

    original_columns = frame.columns.tolist()
    duplicate_columns = frame.columns[frame.columns.duplicated()].tolist()
    if duplicate_columns:
        names = ", ".join(str(column) for column in duplicate_columns)
        raise AutomaticTreeCodegenError(
            f"DuckDB input frame has duplicate columns: {names}"
        )
    non_text_columns = [
        column for column in original_columns if not isinstance(column, str)
    ]
    if non_text_columns:
        names = ", ".join(repr(column) for column in non_text_columns)
        raise AutomaticTreeCodegenError(
            f"DuckDB input column names must all be text: {names}"
        )

    required_fields = {
        field for rule in rules for field in _expression_fields(rule["condition"])
    }
    if additional_feature_fields is not None:
        if isinstance(
            additional_feature_fields, str | bytes | bytearray
        ) or not isinstance(additional_feature_fields, Sequence):
            raise AutomaticTreeCodegenError(
                "additional_feature_fields must be a list of column names"
            )
        normalized_additional: list[str] = []
        for field in additional_feature_fields:
            if not isinstance(field, str) or not field or field != field.strip():
                raise AutomaticTreeCodegenError(
                    "additional_feature_fields must contain canonical column names"
                )
            normalized_additional.append(field)
        if len(normalized_additional) != len(set(normalized_additional)):
            raise AutomaticTreeCodegenError(
                "additional_feature_fields must not contain duplicates"
            )
        required_fields.update(normalized_additional)
    ordered_required_fields = sorted(required_fields)
    original_names = set(original_columns)
    missing_fields = [
        field for field in ordered_required_fields if field not in original_names
    ]
    if missing_fields:
        raise AutomaticTreeCodegenError(
            "DuckDB input frame is missing exact required fields: "
            + ", ".join(missing_fields)
        )

    folded_names: dict[str, str] = {}
    for column in original_columns:
        folded = column.casefold()
        previous = folded_names.get(folded)
        if previous is not None:
            raise AutomaticTreeCodegenError(
                "DuckDB input frame has a case-insensitive column collision: "
                f"{previous}, {column}"
            )
        folded_names[folded] = column

    relation_name = "__marvis_duckdb_input_preflight"
    try:
        with duckdb.connect() as connection:
            connection.register(relation_name, frame)
            relation = connection.table(relation_name)
            registered_columns = relation.columns
            if registered_columns != original_columns:
                raise AutomaticTreeCodegenError(
                    "DuckDB registration changed input column names; the registered "
                    "schema must be byte-identical to the original frame"
                )
            registered_types = [str(value).upper() for value in relation.types]
            _validate_duckdb_weighted_tree_domain(
                connection,
                relation_name=relation_name,
                fields=ordered_required_fields,
                registered_columns=registered_columns,
                registered_types=registered_types,
            )
    except AutomaticTreeCodegenError:
        raise
    except Exception as exc:
        raise AutomaticTreeCodegenError(
            f"DuckDB input schema registration failed: {exc}"
        ) from exc
    return frame


def _validate_duckdb_weighted_tree_domain(
    connection,
    *,
    relation_name: str,
    fields: Sequence[str],
    registered_columns: Sequence[str],
    registered_types: Sequence[str],
) -> None:
    type_by_field = dict(zip(registered_columns, registered_types, strict=True))
    projections: list[str] = []
    for field in fields:
        physical_type = type_by_field[field]
        if physical_type not in (*_DUCKDB_INTEGER_TYPES, *_DUCKDB_FLOAT_TYPES):
            raise AutomaticTreeCodegenError(
                "weighted-tree feature requires an integer/float physical type: "
                + field
            )
        projections.append(
            "COUNT("
            + _sql_validated_weighted_tree_value(_quote_identifier(field))
            + ") AS "
            + _quote_identifier(f"__marvis_validated_{len(projections)}")
        )
    if projections:
        try:
            connection.execute(
                "SELECT "
                + ", ".join(projections)
                + " FROM "
                + _quote_identifier(relation_name)
            ).fetchone()
        except duckdb.Error as exc:
            raise AutomaticTreeCodegenError(str(exc)) from exc


def _validated_leaf_rules(
    tree_or_asset: Mapping[str, Any],
) -> list[dict[str, Any]]:
    if not isinstance(tree_or_asset, Mapping):
        raise AutomaticTreeCodegenError("tree_or_asset must be an object")
    schema_version = tree_or_asset.get("schema_version")
    if schema_version == WEIGHTED_RULE_TREE_SCHEMA_VERSION:
        try:
            tree = validate_weighted_rule_tree(tree_or_asset)
        except (WeightedRuleTreeError, TypeError, ValueError) as exc:
            raise AutomaticTreeCodegenError(
                f"weighted rule tree failed strict validation: {exc}"
            ) from exc
    elif schema_version == AUTOMATIC_TREE_ASSET_SCHEMA_VERSION:
        try:
            asset = validate_automatic_tree_asset(tree_or_asset)
        except (AutomaticTreeAssetError, TypeError, ValueError) as exc:
            raise AutomaticTreeCodegenError(
                f"automatic tree asset failed strict validation: {exc}"
            ) from exc
        tree = asset["tree_result"]
    else:
        raise AutomaticTreeCodegenError(
            "tree_or_asset schema_version must identify a weighted rule tree "
            "or automatic tree asset"
        )
    return _canonical_leaf_rules(
        [
            {
                "leaf_id": rule["leaf_id"],
                "rule_id": rule["rule_id"],
                "condition": rule["condition"],
            }
            for rule in tree["rules"]
        ]
    )


def _canonical_leaf_rules(rules: Sequence[Mapping[str, Any]]) -> list[dict[str, Any]]:
    if isinstance(rules, str | bytes | bytearray) or not isinstance(rules, Sequence):
        raise AutomaticTreeCodegenError("leaf rules must be a list")
    if not rules:
        raise AutomaticTreeCodegenError("leaf rules must not be empty")
    normalized: list[dict[str, Any]] = []
    for index, raw in enumerate(rules):
        if not isinstance(raw, Mapping):
            raise AutomaticTreeCodegenError(f"leaf rules[{index}] must be an object")
        actual = set(raw)
        expected = {"leaf_id", "rule_id", "condition"}
        if actual != expected:
            raise AutomaticTreeCodegenError(f"leaf rules[{index}] fields are invalid")
        leaf_id = _canonical_id(raw["leaf_id"], f"leaf rules[{index}].leaf_id")
        rule_id = _canonical_id(raw["rule_id"], f"leaf rules[{index}].rule_id")
        condition_raw = raw["condition"]
        if not isinstance(condition_raw, Mapping):
            raise AutomaticTreeCodegenError(
                f"leaf rules[{index}].condition must be an object"
            )
        try:
            condition = canonicalize_expression(condition_raw)
        except StrategyError as exc:
            raise AutomaticTreeCodegenError(
                f"leaf rules[{index}].condition is invalid: {exc}"
            ) from exc
        if condition != condition_raw:
            raise AutomaticTreeCodegenError(
                f"leaf rules[{index}].condition must be canonical Strategy DSL"
            )
        normalized.append(
            {"leaf_id": leaf_id, "rule_id": rule_id, "condition": condition}
        )
    for name in ("leaf_id", "rule_id"):
        values = [rule[name] for rule in normalized]
        if len(values) != len(set(values)):
            raise AutomaticTreeCodegenError(f"leaf rule {name}s must be unique")
    return normalized


def _canonical_id(value: object, name: str) -> str:
    if not isinstance(value, str) or not value or value != value.strip():
        raise AutomaticTreeCodegenError(f"{name} must be non-empty canonical text")
    return value


def _generate_python_source_from_leaf_rules(
    rules: Sequence[Mapping[str, Any]],
    *,
    enforce_weighted_tree_domain: bool = False,
) -> str:
    """Internal generic DSL seam used to test the delivery interpreter."""

    canonical = _canonical_leaf_rules(rules)
    fields = sorted(
        {field for rule in canonical for field in _expression_fields(rule["condition"])}
    )
    rules_json = _canonical_json(canonical)
    fields_json = _canonical_json(fields)
    return (
        _PYTHON_TEMPLATE.substitute(
            marvis_rules_json_literal=json.dumps(rules_json, ensure_ascii=True),
            marvis_fields_json_literal=json.dumps(fields_json, ensure_ascii=True),
            marvis_enforce_weighted_tree_domain=(
                "True" if enforce_weighted_tree_domain else "False"
            ),
        ).rstrip()
        + "\n"
    )


def _generate_duckdb_sql_from_leaf_rules(
    rules: Sequence[Mapping[str, Any]],
) -> str:
    """Compile DSL for a prevalidated weighted-tree DuckDB input relation."""

    canonical = _canonical_leaf_rules(rules)
    fields = sorted(
        {field for rule in canonical for field in _expression_fields(rule["condition"])}
    )
    aliases = {field: f"__marvis_field_{index}" for index, field in enumerate(fields)}
    raw_aliases = {
        field: f"__marvis_raw_field_{index}" for index, field in enumerate(fields)
    }
    compiler = _DuckDBExpressionCompiler(aliases)
    conditions = [compiler.compile(rule["condition"]) for rule in canonical]

    type_contract = " AND ".join(
        _sql_weighted_tree_type_contract(field) for field in fields
    )
    exact_columns = [
        '    CAST(ROW_NUMBER() OVER () - 1 AS BIGINT) AS "__marvis_row_ordinal"'
    ]
    exact_columns.extend(
        "    COLUMNS(c -> c = "
        f"{_sql_literal(field)}) AS {_quote_identifier(raw_aliases[field])}"
        for field in fields
    )
    source_columns = ['    "__marvis_row_ordinal"']
    source_columns.extend(
        "    "
        + _sql_validated_weighted_tree_value(_quote_identifier(raw_aliases[field]))
        + f" AS {_quote_identifier(aliases[field])}"
        for field in fields
    )
    flag_columns = ['    "__marvis_row_ordinal"']
    flag_columns.extend(
        f'    ({condition}) AS "__marvis_match_{index}"'
        for index, condition in enumerate(conditions)
    )
    match_names = [f'"__marvis_match_{index}"' for index in range(len(canonical))]
    match_count = " + ".join(f"CAST({name} AS INTEGER)" for name in match_names)
    leaf_case = _routing_case(canonical, match_names, value_key="leaf_id")
    rule_case = _routing_case(canonical, match_names, value_key="rule_id")
    routing_error = _sql_literal("leaf rules must assign every row exactly once")

    lines = [
        "-- Generated by MARVIS automatic-tree codegen. Do not edit.",
        "-- Mandatory: run validate_automatic_tree_duckdb_input_frame on the same frame.",
        "-- Preflight exact duplicates, casefold collisions, and byte-identical schema.",
        "-- Only missing or finite INTEGER/FLOAT values in exact DOUBLE range are accepted.",
        "SET preserve_insertion_order = true;",
        "",
        'WITH "__marvis_exact_input" AS MATERIALIZED (',
        "  SELECT",
        ",\n".join(exact_columns),
        '  FROM "input_rows"',
        "),",
        '"__marvis_source" AS MATERIALIZED (',
        "  SELECT",
        ",\n".join(source_columns),
        '  FROM "__marvis_exact_input"',
        "),",
        '"__marvis_flags" AS MATERIALIZED (',
        "  SELECT",
        ",\n".join(flag_columns),
        '  FROM "__marvis_source"',
        "),",
        '"__marvis_routed" AS MATERIALIZED (',
        "  SELECT",
        '    "__marvis_row_ordinal",',
        f'    {match_count} AS "__marvis_match_count",',
        f'    {leaf_case} AS "__marvis_leaf_id",',
        f'    {rule_case} AS "__marvis_rule_id"',
        '  FROM "__marvis_flags"',
        ")",
        "SELECT",
        '  "__marvis_row_ordinal",',
        "  CASE",
        '    WHEN "__marvis_match_count" = 1 THEN "__marvis_leaf_id"',
        f"    ELSE CAST(ERROR({routing_error}) AS VARCHAR)",
        '  END AS "leaf_id",',
        "  CASE",
        '    WHEN "__marvis_match_count" = 1 THEN "__marvis_rule_id"',
        f"    ELSE CAST(ERROR({routing_error}) AS VARCHAR)",
        '  END AS "rule_id"',
        'FROM "__marvis_routed"',
        'ORDER BY "__marvis_row_ordinal"',
        "LIMIT (SELECT CASE",
        f"  WHEN {type_contract} THEN 4611686018427387904",
        "  ELSE 0",
        "END);",
    ]
    return "\n".join(lines) + "\n"


def _routing_case(
    rules: Sequence[Mapping[str, Any]],
    match_names: Sequence[str],
    *,
    value_key: str,
) -> str:
    branches = " ".join(
        f"WHEN {match_name} THEN {_sql_literal(rule[value_key])}"
        for rule, match_name in zip(rules, match_names, strict=True)
    )
    return f"CASE {branches} ELSE NULL END"


class _DuckDBExpressionCompiler:
    def __init__(self, aliases: Mapping[str, str]) -> None:
        self._aliases = dict(aliases)
        self._n_of_k_counter = 0

    def compile(self, expression: Mapping[str, Any]) -> str:
        op = expression["op"]
        if op == "compare":
            return self._compare(expression)
        if op == "between":
            return self._between(expression)
        if op == "is_null":
            return self._missing(self._field(expression["field"]))
        if op == "is_not_null":
            return f"(NOT {self._missing(self._field(expression['field']))})"
        if op == "and":
            arguments = [self.compile(argument) for argument in expression["args"]]
            result = arguments[-1]
            for argument in reversed(arguments[:-1]):
                result = f"(CASE WHEN {argument} THEN {result} ELSE FALSE END)"
            return result
        if op == "or":
            arguments = [self.compile(argument) for argument in expression["args"]]
            result = arguments[-1]
            for argument in reversed(arguments[:-1]):
                result = f"(CASE WHEN {argument} THEN TRUE ELSE {result} END)"
            return result
        if op == "not":
            return f"(NOT {self.compile(expression['arg'])})"
        if op == "n_of_k":
            arguments = [self.compile(argument) for argument in expression["args"]]
            return self._n_of_k(arguments, required=expression["n"])
        raise AutomaticTreeCodegenError(f"unsupported expression op: {op}")

    def _field(self, field: str) -> str:
        try:
            return _quote_identifier(self._aliases[field])
        except KeyError:
            raise AutomaticTreeCodegenError(
                f"unknown compiled field: {field}"
            ) from None

    def _compare(self, expression: Mapping[str, Any]) -> str:
        value = self._field(expression["field"])
        operator = expression["operator"]
        expected = expression["value"]
        coercion = expression.get("coercion", "auto")
        if operator in {"in", "not_in"}:
            candidates = list(expected)
            if coercion == "strict":
                matched = self._sequential_or(
                    [self._strict_equal(value, item) for item in candidates]
                )
            elif candidates and all(_numeric_literal(item) for item in candidates):
                numeric = self._numeric(value)
                literals = ", ".join(_sql_numeric_literal(item) for item in candidates)
                matched = f"({numeric} IN ({literals}))"
            else:
                matched = self._sequential_or(
                    [self._python_equal(value, item) for item in candidates]
                )
            present = matched if operator == "in" else f"(NOT {matched})"
        elif coercion == "strict":
            matched = self._strict_equal(value, expected)
            present = matched if operator == "==" else f"(NOT {matched})"
        elif operator in {"==", "!="}:
            if _numeric_literal(expected):
                matched = f"({self._numeric(value)} = {_sql_numeric_literal(expected)})"
            else:
                matched = self._python_equal(value, expected)
            present = matched if operator == "==" else f"(NOT {matched})"
        else:
            present = self._ordered_compare(value, operator, expected)
        return self._with_missing(value, expression["missing"], present)

    def _between(self, expression: Mapping[str, Any]) -> str:
        value = self._field(expression["field"])
        lower = expression["lower"]
        upper = expression["upper"]
        lower_operator = ">=" if expression["include_lower"] else ">"
        upper_operator = "<=" if expression["include_upper"] else "<"
        if _numeric_literal(lower) and _numeric_literal(upper):
            comparable = self._numeric(value)
            present = (
                f"(({comparable} {lower_operator} {_sql_numeric_literal(lower)}) "
                f"AND ({comparable} {upper_operator} {_sql_numeric_literal(upper)}))"
            )
        elif isinstance(lower, str) and isinstance(upper, str):
            present = self._typed_ordered_between(
                value,
                type_check=f"(TYPEOF({value}) = 'VARCHAR')",
                comparable=f"CAST({value} AS VARCHAR)",
                lower_operator=lower_operator,
                lower=_sql_literal(lower),
                upper_operator=upper_operator,
                upper=_sql_literal(upper),
            )
        elif _number_or_bool(lower) and _number_or_bool(upper):
            present = self._typed_ordered_between(
                value,
                type_check=self._numeric_or_boolean_type(value),
                comparable=f"TRY_CAST({value} AS DOUBLE)",
                lower_operator=lower_operator,
                lower=_sql_numeric_literal(lower),
                upper_operator=upper_operator,
                upper=_sql_numeric_literal(upper),
            )
        else:
            present = self._error("condition comparison failed")
        return self._with_missing(value, expression["missing"], present)

    def _ordered_compare(self, value: str, operator: str, expected: Any) -> str:
        sql_operator = {"<": "<", "<=": "<=", ">": ">", ">=": ">="}[operator]
        if _numeric_literal(expected):
            return (
                f"({self._numeric(value)} {sql_operator} "
                f"{_sql_numeric_literal(expected)})"
            )
        if isinstance(expected, str):
            return (
                f"(CASE WHEN TYPEOF({value}) = 'VARCHAR' "
                f"THEN CAST({value} AS VARCHAR) {sql_operator} {_sql_literal(expected)} "
                f"ELSE {self._error('condition comparison failed')} END)"
            )
        if isinstance(expected, bool):
            return (
                f"(CASE WHEN {self._numeric_or_boolean_type(value)} "
                f"THEN TRY_CAST({value} AS DOUBLE) {sql_operator} "
                f"{_sql_numeric_literal(expected)} "
                f"ELSE {self._error('condition comparison failed')} END)"
            )
        return self._error("condition comparison failed")

    def _strict_equal(self, value: str, expected: Any) -> str:
        if isinstance(expected, bool):
            return (
                f"(TYPEOF({value}) = 'BOOLEAN' AND "
                f"CAST({value} AS BOOLEAN) IS NOT DISTINCT FROM "
                f"{'TRUE' if expected else 'FALSE'})"
            )
        if _numeric_literal(expected):
            return (
                f"({self._numeric_type(value)} AND "
                f"TRY_CAST({value} AS DOUBLE) = {_sql_numeric_literal(expected)})"
            )
        if isinstance(expected, str):
            return (
                f"(TYPEOF({value}) = 'VARCHAR' AND "
                f"CAST({value} AS VARCHAR) = {_sql_literal(expected)})"
            )
        return "FALSE"

    def _python_equal(self, value: str, expected: Any) -> str:
        if isinstance(expected, bool):
            return (
                f"({self._numeric_or_boolean_type(value)} AND "
                f"TRY_CAST({value} AS DOUBLE) = {_sql_numeric_literal(expected)})"
            )
        if _numeric_literal(expected):
            return (
                f"({self._numeric_or_boolean_type(value)} AND "
                f"TRY_CAST({value} AS DOUBLE) = {_sql_numeric_literal(expected)})"
            )
        if isinstance(expected, str):
            return (
                f"(TYPEOF({value}) = 'VARCHAR' AND "
                f"CAST({value} AS VARCHAR) = {_sql_literal(expected)})"
            )
        if expected is None:
            return "FALSE"
        expected_json = _canonical_json(expected)
        return f"(CAST(TO_JSON({value}) AS VARCHAR) = {_sql_literal(expected_json)})"

    def _numeric(self, value: str) -> str:
        numeric = f"TRY_CAST({value} AS DOUBLE)"
        invalid = f"({numeric} IS NULL OR COALESCE(ISNAN({numeric}), FALSE))"
        return (
            f"(CASE WHEN {invalid} "
            f"THEN CAST(ERROR({_sql_literal('condition comparison failed: field contains a non-numeric value')}) AS DOUBLE) "
            f"ELSE {numeric} END)"
        )

    def _with_missing(self, value: str, policy: str, present: str) -> str:
        if policy == "no_match":
            missing_result = "FALSE"
        elif policy == "match":
            missing_result = "TRUE"
        elif policy == "error":
            missing_result = self._error(
                "condition comparison failed: field value is missing"
            )
        else:
            raise AutomaticTreeCodegenError(f"unsupported missing policy: {policy}")
        return (
            f"(CASE WHEN {self._missing(value)} THEN {missing_result} "
            f"ELSE {present} END)"
        )

    @staticmethod
    def _missing(value: str) -> str:
        return (
            f"({value} IS NULL OR "
            f"(TYPEOF({value}) IN ('FLOAT', 'DOUBLE') AND "
            f"COALESCE(ISNAN(TRY_CAST({value} AS DOUBLE)), FALSE)))"
        )

    @staticmethod
    def _numeric_type(value: str) -> str:
        return (
            f"(TYPEOF({value}) IN ('TINYINT', 'SMALLINT', 'INTEGER', 'BIGINT', "
            "'HUGEINT', 'UTINYINT', 'USMALLINT', 'UINTEGER', 'UBIGINT', "
            f"'UHUGEINT', 'FLOAT', 'DOUBLE') OR STARTS_WITH(TYPEOF({value}), 'DECIMAL('))"
        )

    def _numeric_or_boolean_type(self, value: str) -> str:
        return f"({self._numeric_type(value)} OR TYPEOF({value}) = 'BOOLEAN')"

    def _typed_ordered_between(
        self,
        value: str,
        *,
        type_check: str,
        comparable: str,
        lower_operator: str,
        lower: str,
        upper_operator: str,
        upper: str,
    ) -> str:
        comparison = (
            f"(({comparable} {lower_operator} {lower}) AND "
            f"({comparable} {upper_operator} {upper}))"
        )
        return (
            f"(CASE WHEN {type_check} THEN {comparison} "
            f"ELSE {self._error('condition comparison failed')} END)"
        )

    def _n_of_k(self, arguments: Sequence[str], *, required: int) -> str:
        self._n_of_k_counter += 1
        prefix = f"__marvis_n_of_k_{self._n_of_k_counter}"
        state_names = [
            f'"{prefix}_state_{index}"' for index in range(len(arguments) + 1)
        ]
        lines = [
            f"(SELECT {state_names[-1]} >= {required}",
            f' FROM (SELECT 0::INTEGER AS {state_names[0]}) AS "{prefix}_base"',
        ]
        for index, argument in enumerate(arguments, start=1):
            previous = state_names[index - 1]
            current = state_names[index]
            lines.append(
                " CROSS JOIN LATERAL (SELECT CASE "
                f"WHEN {previous} >= {required} THEN {previous} "
                f"ELSE {previous} + CASE WHEN {argument} THEN 1 ELSE 0 END END "
                f'AS {current}) AS "{prefix}_step_{index}"'
            )
        lines.append(")")
        return "".join(lines)

    @staticmethod
    def _sequential_or(expressions: Sequence[str]) -> str:
        if not expressions:
            return "FALSE"
        result = expressions[-1]
        for expression in reversed(expressions[:-1]):
            result = f"(CASE WHEN {expression} THEN TRUE ELSE {result} END)"
        return result

    @staticmethod
    def _error(message: str) -> str:
        return f"CAST(ERROR({_sql_literal(message)}) AS BOOLEAN)"


def _expression_fields(expression: Mapping[str, Any]) -> tuple[str, ...]:
    op = expression["op"]
    if op in {"compare", "between", "is_null", "is_not_null"}:
        return (expression["field"],)
    if op in {"and", "or", "n_of_k"}:
        return tuple(
            field
            for argument in expression["args"]
            for field in _expression_fields(argument)
        )
    if op == "not":
        return _expression_fields(expression["arg"])
    raise AutomaticTreeCodegenError(f"unsupported expression op: {op}")


def _numeric_literal(value: object) -> bool:
    return isinstance(value, Real) and not isinstance(value, bool)


def _number_or_bool(value: object) -> bool:
    return isinstance(value, bool) or _numeric_literal(value)


def _sql_numeric_literal(value: int | float | bool) -> str:
    if isinstance(value, bool):
        return "1.0" if value else "0.0"
    return f"CAST({_sql_literal(json.dumps(value, allow_nan=False))} AS DOUBLE)"


def _sql_validated_weighted_tree_value(value: str) -> str:
    value_type = f"TYPEOF({value})"
    integer_types = ", ".join(_sql_literal(item) for item in _DUCKDB_INTEGER_TYPES)
    float_types = ", ".join(_sql_literal(item) for item in _DUCKDB_FLOAT_TYPES)
    decimal = f"TRY_CAST({value} AS DECIMAL(38, 0))"
    exact_limit = (
        f"CAST({_sql_literal(str(_MAX_EXACT_DOUBLE_INTEGER))} AS DECIMAL(38, 0))"
    )
    type_error = _sql_literal(
        "weighted-tree feature requires an integer/float physical type"
    )
    range_error = _sql_literal("weighted-tree integer exceeds the exact DOUBLE range")
    finite_error = _sql_literal("weighted-tree feature must be finite or missing")
    return (
        "(CASE "
        f"WHEN {value_type} IN ({integer_types}) THEN CASE "
        f"WHEN {value} IS NULL THEN {value} "
        f"WHEN {decimal} IS NULL OR {decimal} < -{exact_limit} "
        f"OR {decimal} > {exact_limit} "
        f"THEN ERROR({range_error}) ELSE {value} END "
        f"WHEN {value_type} IN ({float_types}) THEN CASE "
        f"WHEN COALESCE(ISINF(TRY_CAST({value} AS DOUBLE)), FALSE) "
        f"THEN ERROR({finite_error}) ELSE {value} END "
        f"ELSE ERROR({type_error}) END)"
    )


def _sql_weighted_tree_type_contract(field: str) -> str:
    allowed_types = ", ".join(
        _sql_literal(item) for item in (*_DUCKDB_INTEGER_TYPES, *_DUCKDB_FLOAT_TYPES)
    )
    exact_column = (
        f'(SELECT COLUMNS(c -> c = {_sql_literal(field)}) FROM "input_rows" LIMIT 1)'
    )
    type_error = _sql_literal(
        "weighted-tree feature requires an integer/float physical type"
    )
    return (
        f"CASE WHEN TYPEOF({exact_column}) IN ({allowed_types}) "
        f"THEN TRUE ELSE ERROR({type_error}) END"
    )


def _quote_identifier(value: str) -> str:
    if "\x00" in value:
        raise AutomaticTreeCodegenError("DuckDB identifiers cannot contain NUL")
    return '"' + value.replace('"', '""') + '"'


def _sql_literal(value: str) -> str:
    if "\x00" in value:
        raise AutomaticTreeCodegenError("DuckDB text literals cannot contain NUL")
    return "'" + value.replace("'", "''") + "'"


def _canonical_json(value: object) -> str:
    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        )
    except (TypeError, ValueError) as exc:
        raise AutomaticTreeCodegenError(
            "leaf rules must contain finite canonical JSON"
        ) from exc


__all__ = [
    "AutomaticTreeCodegenError",
    "generate_automatic_tree_duckdb_sql_source",
    "generate_automatic_tree_python_source",
    "validate_automatic_tree_duckdb_input_frame",
]
