from __future__ import annotations

from marvis.orchestrator.templates import _register_builtin_template
from marvis.orchestrator.templates.data import DATASET_DESCRIPTIVE_ANALYSIS
from marvis.orchestrator.templates.data_export import DATASET_EXPORT
from marvis.orchestrator.templates.data_transform import DATASET_TRANSFORM
from marvis.orchestrator.templates.feature import (
    FEATURE_ANALYSIS,
    FEATURE_ANALYSIS_WITH_JOIN,
    FEATURE_DERIVATION,
)
from marvis.orchestrator.templates.join import DATA_JOIN
from marvis.orchestrator.templates.labeling import LABEL_CONSTRUCTION
from marvis.orchestrator.templates.modeling import (
    MODELING,
    MODELING_WITH_JOIN,
    STANDARD_MODELING,
)
from marvis.orchestrator.templates.monitoring import MONITORING_RUN, STRATEGY_MONITORING
from marvis.orchestrator.templates.portfolio import (
    PORTFOLIO_ANALYSIS,
    PORTFOLIO_ANALYSIS_NO_TREND,
)
from marvis.orchestrator.templates.sample_echo import SAMPLE_ECHO
from marvis.orchestrator.templates.strategy import (
    DETERMINISTIC_STRATEGY_CANDIDATE_DEVELOPMENT,
    RULE_STRATEGY,
    SLICE_AGGREGATE,
    STORED_STRATEGY_ADOPTION,
    STORED_STRATEGY_APPLY,
    STORED_STRATEGY_EVALUATION,
    STORED_STRATEGY_REPORT,
    STRATEGY_ANALYSIS,
    STRATEGY_AUTOMATIC_TREE_APPLY,
    STRATEGY_AUTOMATIC_TREE_CANDIDATE_BUILD,
    STRATEGY_AUTOMATIC_TREE_LEAF_MATERIALIZATION,
    STRATEGY_INTERACTIVE_TREE_FRONTIER_GROUP_MATERIALIZATION,
    STRATEGY_INTERACTIVE_TREE_FRONTIER_MATERIALIZATION,
    STRATEGY_INTERACTIVE_TREE_REVISION,
    STRATEGY_CANDIDATE_MONTHLY_STABILITY,
    STRATEGY_CROSS_MATRIX_ANALYSIS,
    STRATEGY_CROSS_MATRIX_CELL_SELECTION,
    STRATEGY_DEVELOPMENT,
    STRATEGY_DSL_DELIVERY,
    STRATEGY_LIMIT_PRICING_ANALYSIS,
    STRATEGY_IMPACT_CUBE,
    STRATEGY_POOL_STABILITY,
    STRATEGY_MODEL_EVIDENCE_V2,
    STRATEGY_POOL_ADD_CANDIDATE,
    STRATEGY_POOL_APPLY,
    STRATEGY_POOL_COMPILE,
    STRATEGY_POOL_IMPACT,
    STRATEGY_POOL_VALIDATION,
    STRATEGY_POOL_REMOVE_ENTRY,
    STRATEGY_POOL_REORDER,
    STRATEGY_POOL_SET_ACTION,
    STRATEGY_PROFIT_ANALYSIS,
    STRATEGY_PROJECT_CONTEXT,
    STRATEGY_REPORT_BUNDLE_V2,
    STRATEGY_ROLL_RATE_ANALYSIS,
    STRATEGY_SAMPLE_DESIGN,
    STRATEGY_SAMPLE_DESIGN_V2,
    STRATEGY_SCORECARD_BAND_BUILD,
    STRATEGY_SCORECARD_CUTOFF_SELECTION,
    STRATEGY_UNIVARIATE_CANDIDATE_ANALYSIS,
    STRATEGY_UNIVARIATE_CANDIDATE_REFINEMENT,
    STRATEGY_UNIVARIATE_CANDIDATE_REFINEMENT_EXISTING,
    STRATEGY_VOTING_CANDIDATE_BUILD,
    STRATEGY_VOTING_CANDIDATE_BUILD_FROM_SEARCH,
    STRATEGY_VOTING_CANDIDATE_SEARCH,
    TYPED_STRATEGY_APPLY,
    TYPED_STRATEGY_BUILD,
    TYPED_STRATEGY_EVALUATION,
    VINTAGE_ANALYSIS,
)
from marvis.orchestrator.templates.validation import MODEL_VALIDATION

# This module is the builtin-template aggregation facade: the template
# definitions themselves live in per-domain modules below; this file only wires
# them into the registry in the product display order.
BUILTIN_TEMPLATES = (
    SAMPLE_ECHO,
    DATASET_DESCRIPTIVE_ANALYSIS,
    DATASET_TRANSFORM,
    DATASET_EXPORT,
    MODEL_VALIDATION,
    STANDARD_MODELING,
    DATA_JOIN,
    LABEL_CONSTRUCTION,
    MODELING,
    MODELING_WITH_JOIN,
    FEATURE_ANALYSIS,
    FEATURE_ANALYSIS_WITH_JOIN,
    FEATURE_DERIVATION,
    STRATEGY_ANALYSIS,
    STRATEGY_DEVELOPMENT,
    STRATEGY_PROFIT_ANALYSIS,
    STRATEGY_ROLL_RATE_ANALYSIS,
    STRATEGY_PROJECT_CONTEXT,
    STRATEGY_SAMPLE_DESIGN,
    STRATEGY_SAMPLE_DESIGN_V2,
    STRATEGY_MODEL_EVIDENCE_V2,
    STRATEGY_UNIVARIATE_CANDIDATE_ANALYSIS,
    STRATEGY_CROSS_MATRIX_ANALYSIS,
    STRATEGY_CROSS_MATRIX_CELL_SELECTION,
    STRATEGY_AUTOMATIC_TREE_CANDIDATE_BUILD,
    STRATEGY_AUTOMATIC_TREE_APPLY,
    STRATEGY_VOTING_CANDIDATE_SEARCH,
    STRATEGY_VOTING_CANDIDATE_BUILD_FROM_SEARCH,
    STRATEGY_VOTING_CANDIDATE_BUILD,
    STRATEGY_AUTOMATIC_TREE_LEAF_MATERIALIZATION,
    STRATEGY_INTERACTIVE_TREE_REVISION,
    STRATEGY_INTERACTIVE_TREE_FRONTIER_GROUP_MATERIALIZATION,
    STRATEGY_INTERACTIVE_TREE_FRONTIER_MATERIALIZATION,
    STRATEGY_UNIVARIATE_CANDIDATE_REFINEMENT,
    STRATEGY_UNIVARIATE_CANDIDATE_REFINEMENT_EXISTING,
    STRATEGY_CANDIDATE_MONTHLY_STABILITY,
    STRATEGY_SCORECARD_BAND_BUILD,
    STRATEGY_SCORECARD_CUTOFF_SELECTION,
    STRATEGY_POOL_ADD_CANDIDATE,
    STRATEGY_POOL_REMOVE_ENTRY,
    STRATEGY_POOL_SET_ACTION,
    STRATEGY_POOL_REORDER,
    STRATEGY_POOL_COMPILE,
    STRATEGY_POOL_APPLY,
    STRATEGY_POOL_VALIDATION,
    STRATEGY_POOL_IMPACT,
    STRATEGY_IMPACT_CUBE,
    STRATEGY_POOL_STABILITY,
    STRATEGY_DSL_DELIVERY,
    STRATEGY_REPORT_BUNDLE_V2,
    STRATEGY_LIMIT_PRICING_ANALYSIS,
    DETERMINISTIC_STRATEGY_CANDIDATE_DEVELOPMENT,
    TYPED_STRATEGY_APPLY,
    TYPED_STRATEGY_BUILD,
    TYPED_STRATEGY_EVALUATION,
    STORED_STRATEGY_EVALUATION,
    STORED_STRATEGY_REPORT,
    STORED_STRATEGY_APPLY,
    STORED_STRATEGY_ADOPTION,
    RULE_STRATEGY,
    VINTAGE_ANALYSIS,
    SLICE_AGGREGATE,
    MONITORING_RUN,
    STRATEGY_MONITORING,
    PORTFOLIO_ANALYSIS,
    PORTFOLIO_ANALYSIS_NO_TREND,
)


def register_all_builtin_templates() -> None:
    for template in BUILTIN_TEMPLATES:
        _register_builtin_template(template)


register_all_builtin_templates()
